name: Mio Russian Daily Lessons

on:
  schedule:
# ၅ မိနစ်တစ်ခါ အလုပ်လုပ်ရန်
    - cron: '*/5 * * * *'
  workflow_dispatch:

jobs:
  send-lesson:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4  # ဒီနေရာကို ပြင်လိုက်ပါပြီ
        with:
          python-version: '3.9'

      - name: Install dependencies
        run: pip install requests

      - name: Run script
        env:
          BOT_TOKEN: ${{ secrets.BOT_TOKEN }}
          CHAT_ID: ${{ secrets.CHAT_ID }}
        run: python main.py
